name: Python application test with Github Actions

# 在master分支发生push事件时触发。
on:
    push:
      branches:
        - main

env: # 设置环境变量
    TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用该时区时间）

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [3.6, 3.7, 3.8, 3.9]
    
        steps:
            - name: Checkout # 步骤1
              uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
        
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
            - name: Run tests
              run: |
                python main.py --test